### ISSUE TITLE
Compatibility issues with G&K ruleset

### ISSUE THREAD

**Issue by Marcos6226** [GeneralWadaling/Warfare-Expanded-Unciv-Bucketeer#4]
For some reason, when I go to the "locate mod errors" option to check if there is any issue the mods, this warning shows up when I run a check on your mod with the Civ-5 Gods and Kings ruleset as a base. (as shown in the screenshots).

Can't say for sure if it affects the gameplay in any way but I would prefer to not ignore such warnings. (Notice that I have the latest version of your mod [at the time of writing this message: May 30th, 2022] and the version of my game is [4.1.4-patch1](https://github.com/yairm210/Unciv/releases/tag/4.1.4-patch1) )

![Screenshot_2022-05-30-13-12-46](https://user-images.githubusercontent.com/49823690/171031043-27451e86-3f5d-4210-b442-538864df430c.png)

![Screenshot_2022-05-30-13-12-36](https://user-images.githubusercontent.com/49823690/171031050-245ef1a5-dee3-4e78-bf3c-e9cc115ac3d6.png)

And this is the full warning log that appeared to me: 《 Special Promotion's unique "This Unit upgrades for free including special upgrades" cannot be put on this type of object!
Land Dreadnought's unique "Eliminates combat penalty for attacking from the sea" is deprecated as of 3.19.8, replace with "Eliminates combat penalty for attacking across a coast"
Land Dreadnought's unique "Not displayed as an available construction without [Secret Project]" is deprecated as of 3.19.8, replace with "Only available <with [Secret Project]>"
Superheavy Tank's unique "Not displayed as an available construction without [Secret Project]" is deprecated as of 3.19.8, replace with "Only available <with [Secret Project]>"
Apoclaypse Missile's unique "Not displayed as an available construction without [Secret Project]" is deprecated as of 3.19.8, replace with "Only available <with [Secret Project]>"
Orbital Strike Satellite's unique "Not displayed as an available construction without [Secret Project]" is deprecated as of 3.19.8, replace with "Only available <with [Secret Project]>"
Cloning Facility's unique "Not displayed as an available construction without [Secret Project]" is deprecated as of 3.19.8, replace with "Only available <with [Secret Project]>"
ARENA Defense System's unique "Not displayed as an available construction without [Secret Project]" is deprecated as of 3.19.8, replace with "Only available <with [Secret Project]>"
Iron Curtain's unique "Not displayed as an available construction without [Secret Project]" is deprecated as of 3.19.8, replace with "Only available <with [Secret Project]>"
Longship's unique "Heals [10] damage if it kills a Unit" looks like it may be a misspelling of:
	"Heals [amount] damage if it kills a unit"
Technical's unique "Heals [15] damage if it kills a Unit" looks like it may be a misspelling of:
	"Heals [amount] damage if it kills a unit"
Battlefield Survival II's unique "Heals [20] damage if it kills a Unit" looks like it may be a misspelling of:
	"Heals [amount] damage if it kills a unit"
Longship's unique "Heals [10] damage if it kills a Unit" looks like it may be a misspelling of:
	"Heals [amount] damage if it kills a unit"
Technical's unique "Heals [15] damage if it kills a Unit" looks like it may be a misspelling of:
	"Heals [amount] damage if it kills a unit"
Peace Loving's unique "[+1 Happiness] for every [5] global followers [in non-enemy foreign cities]" looks like it may be a misspelling of:
	"[stats] from every [amount] global followers [cityFilter]"
Tithe's unique "[+1 Gold] for every [4] global followers [in all cities]" looks like it may be a misspelling of:
	"[stats] from every [amount] global followers [cityFilter]"
World Church's unique "[+1 Culture] for every [5] global followers [in foreign cities]" looks like it may be a misspelling of:
	"[stats] from every [amount] global followers [cityFilter]"
Battlefield Survival II's unique "Heals [20] damage if it kills a Unit" looks like it may be a misspelling of:
	"Heals [amount] damage if it kills a unit" 》

**Comment by GeneralWadaling** [comment]
I'll check and update the codes.

**Comment by GeneralWadaling** [comment]
All obsolete codes replaced with new! :)

**Comment by Marcos6226** [comment]
> All obsolete codes replaced with new! :)

Thanks, I really liked that mod. Keep up your excellent work!
